// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type HomepageDocumentDataSlicesSlice =
  | EditorsPlaygroundSlice
  | BentoBoxSlice
  | HeroSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

/**
 * Content for Switch documents
 */
interface SwitchDocumentData {
  /**
   * Name field in *Switch*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: switch.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * HexColor field in *Switch*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: switch.color
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  color: prismic.ColorField;
}

/**
 * Switch document from Prismic
 *
 * - **API ID**: `switch`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SwitchDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<SwitchDocumentData>, "switch", Lang>;

export type AllDocumentTypes = HomepageDocument | SwitchDocument;

/**
 * Item in *BentoBox → Default → Primary → Items*
 */
export interface BentoBoxSliceDefaultPrimaryItemsItem {
  /**
   * Size field in *BentoBox → Default → Primary → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: bento_box.default.primary.items[].size
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  size: prismic.SelectField<"Small" | "Medium" | "Large">;

  /**
   * Image field in *BentoBox → Default → Primary → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: bento_box.default.primary.items[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Text field in *BentoBox → Default → Primary → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bento_box.default.primary.items[].text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;
}

/**
 * Primary content in *BentoBox → Default → Primary*
 */
export interface BentoBoxSliceDefaultPrimary {
  /**
   * Heading field in *BentoBox → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bento_box.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Items field in *BentoBox → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: bento_box.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  items: prismic.GroupField<Simplify<BentoBoxSliceDefaultPrimaryItemsItem>>;

  /**
   * Switch field in *BentoBox → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: bento_box.default.primary.switch
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  switch: ContentRelationshipFieldWithData<
    [{ id: "switch"; fields: ["name", "color"] }]
  >;
}

/**
 * Default variation for BentoBox Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BentoBoxSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BentoBoxSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BentoBox*
 */
type BentoBoxSliceVariation = BentoBoxSliceDefault;

/**
 * BentoBox Shared Slice
 *
 * - **API ID**: `bento_box`
 * - **Description**: BentoBox
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BentoBoxSlice = prismic.SharedSlice<
  "bento_box",
  BentoBoxSliceVariation
>;

/**
 * Item in *EditorsPlayground → Default → Primary → Switches*
 */
export interface EditorsPlaygroundSliceDefaultPrimarySwitchesItem {
  /**
   * Switch field in *EditorsPlayground → Default → Primary → Switches*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: editors_playground.default.primary.switches[].switch
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  switch: ContentRelationshipFieldWithData<
    [{ id: "switch"; fields: ["name", "color"] }]
  >;
}

/**
 * Primary content in *EditorsPlayground → Default → Primary*
 */
export interface EditorsPlaygroundSliceDefaultPrimary {
  /**
   * Heading field in *EditorsPlayground → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: editors_playground.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *EditorsPlayground → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: editors_playground.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Switches field in *EditorsPlayground → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: editors_playground.default.primary.switches[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  switches: prismic.GroupField<
    Simplify<EditorsPlaygroundSliceDefaultPrimarySwitchesItem>
  >;
}

/**
 * Default variation for EditorsPlayground Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type EditorsPlaygroundSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<EditorsPlaygroundSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *EditorsPlayground*
 */
type EditorsPlaygroundSliceVariation = EditorsPlaygroundSliceDefault;

/**
 * EditorsPlayground Shared Slice
 *
 * - **API ID**: `editors_playground`
 * - **Description**: EditorsPlayground
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type EditorsPlaygroundSlice = prismic.SharedSlice<
  "editors_playground",
  EditorsPlaygroundSliceVariation
>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Heading field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Body field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;

  /**
   * Code Playground field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.code_playground
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  code_playground: prismic.KeyTextField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      SwitchDocument,
      SwitchDocumentData,
      AllDocumentTypes,
      BentoBoxSlice,
      BentoBoxSliceDefaultPrimaryItemsItem,
      BentoBoxSliceDefaultPrimary,
      BentoBoxSliceVariation,
      BentoBoxSliceDefault,
      EditorsPlaygroundSlice,
      EditorsPlaygroundSliceDefaultPrimarySwitchesItem,
      EditorsPlaygroundSliceDefaultPrimary,
      EditorsPlaygroundSliceVariation,
      EditorsPlaygroundSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
    };
  }
}
