import type { Metadata } from "next";
import { Roboto_Flex} from "next/font/google";
import "./globals.css";
import { Footer } from "@/components/Footer";

const robotoFlex = Roboto_Flex({
  variable: "--font-roboto-flex",
  subsets: ["latin"],
  display: "swap",
  axes: ["wdth" , "slnt", "opsz"]
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${robotoFlex.variable} antialiased`}
      >

        <main className="flex-grow">
            {children}
        </main>

        <Footer />
        
      </body>
    </html>
  );
}
